version: "3.9"

services:
  backend:
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://agent:supersecurepassword@postgres:5432/agent
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: agent
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  pgdata:
