version: "3.9"

services:
  backend:
    container_name: agent-zero-backend
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://agent:supersecurepassword@postgres:5432/agent
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: agent-zero-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: agent
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: agent-zero-redis
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
